### ISSUE TITLE
Non "Long" type for Id

### ISSUE THREAD

**Issue by smurfy** [eXsio/nestedj#1]
Hi,

sorry maybe its easy but i'm new to java (kotlin), i have a problem using an UUID as id instead of a Long value.

For example the default JPARepository supports providing the type of id ``JpaRepository<Category, UUID>``

But within ``NestedNode`` getId is defined as `` Long getId();``  same goes for ``getNodeInfo`` within the receiver, so Long's everywhere :)

**Comment by smurfy** [comment]
Thanks for the quick reply, i checked multiple libs, while all have the Long problem, yours looked the cleanest. I also really like the abstraction of the multiple parts so its easier to integrate different behaviour.

For example i also need multiple "root" entries, but that should be fairly easy, as you described in you readme.

**Comment by eXsio** [comment]
Hi smurfy

Well this one was created some time ago and has undergone some refactorings to keep it clean :) As for the parametrized ID type, please check out version 2.2.0. It should have everything you need. I've also moved some things around and created some static convenience builders on the ```NestedNodeRepository``` interface. Hope that solves you problems. If everything works as expected please comment and close the issue.

**Comment by smurfy** [comment]
Thank you works.
