### ISSUE TITLE
lock

### ISSUE THREAD

**Issue by ben33880** [eXsio/nestedj#11]
Its not a bug report.

Can u give a lock exemple ?
Thanks for ur library.

**Comment by ben33880** [comment]
If i put a version column in model for optimistic lock, is it sufficient?

**Comment by eXsio** [comment]
Sorry for late response.

You should always lock either a whole tree (according to your tree discriminator) or entire table. Every operation clauses modification of multiple db rows.

**Comment by ben33880** [comment]
Thanks u for response.
Will try in memory and try to understand how it works.
