### ISSUE TITLE
Slow rebuildTree

### ISSUE THREAD

**Issue by CaiusBallad** [eXsio/nestedj#13]
In my test, while the nodes exceed about 100, the delete(with rebuildTree every time) will be very slow, about 10s, is something I did wrong?

**Comment by eXsio** [comment]
Why would you rebuild the tree upon every delete? Delete shouldn't make the tree invalid so it won't need to be rebuilt.

Rebuild is a very costly operation and should be done only if the tree was modified outside of NestedJ (for example by manual DML execution)

**Comment by CaiusBallad** [comment]
Got it, thanks!
