### ISSUE TITLE
rebuild tree logic doubt

### ISSUE THREAD

**Issue by archfish** [eXsio/nestedj#15]
When i insert new record, the whole tree was updated; Maybe there shuld reverse build the tree.

Using spring boot 2.3.6 and JdbcTreeDiscriminator.

```xml
<dependency>
	<groupId>com.github.eXsio</groupId>
	<artifactId>nestedj</artifactId>
	<version>5.0.3</version>
</dependency>
```

![image](https://user-images.githubusercontent.com/5317064/103073249-49627400-4602-11eb-9cce-ee709706798e.png)

![image](https://user-images.githubusercontent.com/5317064/103073276-51baaf00-4602-11eb-978e-a312e5b1fe21.png)

-----

测试树重建的时候发现树的生成是数据越新（id 越大）的lft和rgt的值越大，这会导致新插入数据时整个树的编号都要更新。
如果让树反向生长则数据插入时只有新插入的数据受影响。

或者我使用的姿势有问题？

**Comment by eXsio** [comment]
Hello

Yes, inserting node will trigger updates to multiple nodes. Its how nested set works. I've mentioned this also in readme:

Any update of the tree structure triggers cascade update of left/right/level values in multiple nodes. NestedJ should only be considered when the reads count highly outnumbers the modifications count.

**Comment by archfish** [comment]
> Hello
> 
> Yes, inserting node will trigger updates to multiple nodes. Its how nested set works. I've mentioned this also in readme:
> 
> Any update of the tree structure triggers cascade update of left/right/level values in multiple nodes. NestedJ should only be considered when the reads count highly outnumbers the modifications count.

Got it! Thanks!
