### ISSUE TITLE
How do I use the discriminator?

### ISSUE THREAD

**Issue by azdanov** [eXsio/nestedj#17]
For example, I have nested sets of countries > states > cities.
I'd like to have separate trees with each country as a root node.

But I can't seem to understand the test example in JPA:

https://github.com/eXsio/nestedj/blob/e1e763baa6e1ac2c299c3add1e65941123b5baf2/src/test/java/pl/exsio/nestedj/config/jpa/discriminator/TestJpaTreeDiscriminator.java#L10

This way I can only have 1 discriminator for 'tree_1', but how do I add 'tree_2', 'tree_3', and so on?

Previously I've worked with https://github.com/lazychaser/laravel-nestedset which doesn't seem to have this concept.

**Comment by eXsio** [comment]
Hello, thank you for using NestedJ. There was a similar question asked some time before - you can store the actual value of the discriminator in for example a ThreadLocal instance:

https://github.com/eXsio/nestedj/issues/9

**Comment by azdanov** [comment]
I see, thank you.

I'm trying to decide if I need a discriminator or not, since using a ThreadLocal complicates the code quite a bit.

In which case a discriminator is necessary? Since I've tried populating a db without it, and it seems to be working fine.

I've used this data as an example, where I get 2 trees with the USA and Estonia having `parentId=null`: 
```json
[
  {
    "name": "USA",
    "children": [
      {
        "name": "Alabama",
        "children": [
          {
            "name": "Auburn"
          },
          {
            "name": "Birmingham"
          },
          {
            "name": "Dothan"
          }
        ]
      },
      {
        "name": "Alaska",
        "children": [
          {
            "name": "Anchorage / Mat-su"
          },
          {
            "name": "Fairbanks"
          },
          {
            "name": "Kenai Peninsula"
          }
        ]
      }
    ]
  },
  {
    "name": "Estonia",
    "children": [
      {
        "name": "Harjumaa",
        "children": [
          {
            "name": "Tallinn"
          },
          {
            "name": "Maardu"
          },
          {
            "name": "Keila"
          }
        ]
      },
      {
        "name": "Tartumaa",
        "children": [
          {
            "name": "Tartu"
          },
          {
            "name": "Elva"
          },
          {
            "name": "Kambja"
          }
        ]
      }
    ]
  }
]
```

Would this be a correct way of setting the discriminator? And how can I verify that it's working?
```java
private void loadAreas() throws IOException {
  ObjectMapper mapper = new ObjectMapper();

  List<AreaTreeDTO> countries =
      mapper.readValue(
          ResourceUtils.getFile("classpath:areas.json"),
          mapper.getTypeFactory().constructCollectionType(List.class, AreaTreeDTO.class));

  countries.forEach(
      countryDTO -> {
        String countrySlug = this.slugify.slugify(countryDTO.name());
        Area country = new Area(countryDTO.name(), countrySlug);
        country.setDiscriminator(countrySlug);
        AreaTreeDiscriminator.setAreaDiscriminator(countrySlug);
        areaNestedNodeRepository.insertAsLastRoot(country);

        countryDTO
            .children()
            .forEach(
                stateDTO -> {
                  String stateSlug =
                      this.slugify.slugify(countryDTO.name() + " " + stateDTO.name());
                  Area state = new Area(stateDTO.name(), stateSlug);
                  state.setDiscriminator(countrySlug);
                  areaNestedNodeRepository.insertAsLastChildOf(state, country);

                  stateDTO
                      .children()
                      .forEach(
                          cityDTO -> {
                            String citySlug =
                                this.slugify.slugify(stateDTO.name() + " " + cityDTO.name());
                            Area city = new Area(cityDTO.name(), citySlug);
                            city.setDiscriminator(countrySlug);
                            areaNestedNodeRepository.insertAsLastChildOf(city, state);
                          });
                });
      });
  
  AreaTreeDiscriminator.cleanupDiscriminator();
}
```

```java
public class AreaTreeDiscriminator extends MapJpaTreeDiscriminator<Integer, Area> {

  private static final ThreadLocal<String> AREA_DISCRIMINATOR = new ThreadLocal<>();

  public static void setAreaDiscriminator(String areaDiscriminator) {
    AREA_DISCRIMINATOR.set(areaDiscriminator);
  }

  public static void cleanupDiscriminator() {
    AREA_DISCRIMINATOR.remove();
  }

  public AreaTreeDiscriminator() {
    super(Collections.singletonMap("discriminator", AREA_DISCRIMINATOR::get));
  }
}
```

And thank you for your time in helping me out :)

**Comment by eXsio** [comment]
No problem ;) in general Discriminator should be used when:
- you have multiple logically - separated Trees in one Table. A good example would be multitenancy - each Tenant should have its own nodes hierarchy. As you know Tree modification updates multiple nodes and as a rule, Tenants should modify only their own data, not data belonging to other Tenants.
- if you have a very large Tree with multiple Roots, it can be beneficial from the performance and concurrency side to treat Root ID as a discriminator, so that while updating branch on one Root, the other Roots are not affected nor locked in the database.

In other cases I wouldn't go with discriminator, as it complicates the logic. All operations on the table will be fast, assuming that it is properly indexed.

**Comment by azdanov** [comment]
I understand it better now, thank you for a thorough answer. :)
