### ISSUE TITLE
Join Fetch whole tree

### ISSUE THREAD

**Issue by azdanov** [eXsio/nestedj#18]
Is it possible to fetch the whole tree from the database?
I've noticed that when I mapped an entity to dto there was a db operation for each tree node.

Ideally I'd like to fetch the 'roots' (2 in this case) with each tree fully available, otherwise this created an n+1.

<details>
<summary>Example</summary>

```java
@Cacheable
@Override
@Transactional(readOnly = true)
public List<AreaTreeDTO> getAllAreas() {
  List<Area> roots = areaRepository.findAllByParentIdIsNull();

  return roots.stream()
      .map(country -> getAreaTreeDTORecursive(areaNestedNodeRepository.getTree(country)))
      .toList();
}

private AreaTreeDTO getAreaTreeDTORecursive(Tree<Integer, Area> tree) {
  Area area = tree.getNode();
  List<Tree<Integer, Area>> children = tree.getChildren();
  return new AreaTreeDTO(area.getName(), area.getSlug(), processTreeList(children));
}

private List<AreaTreeDTO> processTreeList(List<Tree<Integer, Area>> treeList) {
  return treeList.stream().map(this::getAreaTreeDTORecursive).toList();
}
```

<img width="1280" alt="Screenshot 2021-05-30 at 20 45 58" src="https://user-images.githubusercontent.com/6123841/120114501-1bbcc080-c188-11eb-9c01-6dee9080b2a6.png">

</details>

**Comment by eXsio** [comment]
Hi

There is a number of ways you can do that:
- you can select all nodes with a given discriminator value (if you're using discriminators of course)
- if you want to fetch a concrete branch of a Tree, you can use ```where tree_left < parent_left and tree_right > parent_right``` clause to fetch all nodes. Nested Set is constructed in a way that doesn't require to use joins to fetch child/parent nodes. You just have to properly operate on left/right/level values of nodes.

**Comment by azdanov** [comment]
Thanks, I'll see if I figure it out in JPA.
