### ISSUE TITLE
I can't config NestedNodeRepository interface, can you help me?

### ISSUE THREAD

**Issue by phuchoang502** [eXsio/nestedj#19]
Hello, I'm a beginner Java web, I can't config NestedNodeRepository, it has error "Consider defining a bean of type 'com.Lab5.Repository.CategoryNestedRepository' in your configuration.",is it the same as using JpaRepository, I don't understand how to use it, please help, thanks.

**Comment by eXsio** [comment]
Hello

If I understand correctly you are using Spring Framework, is that correct?

If yes, please take a look at this class: https://github.com/eXsio/nestedj/blob/master/src/test/java/pl/exsio/nestedj/TestConfiguration.java

It shows exactly how to configure a Repository of each available type.
