### ISSUE TITLE
PrevSibling/NextSibling

### ISSUE THREAD

**Issue by rollenwiese** [eXsio/nestedj#2]
Hey are you by any chance interested in a pull request that adds methods and related unit tests for retrieving next and previous sibling nodes?

https://github.com/rollenwiese/nestedj/commit/ad56143678261ed7f0d4bf0b8984a657738fa169

The _get_siblings_ branch in my repo should merge without issue.

**Comment by eXsio** [comment]
Hello

Thanks for taking the interest in nestedj :)

Your changes look interesting and I would welcome the PR that contains
them. There's just one thing I was wandering - do we really need the
following condition?:

if (node.getTreeLevel() > 0)

What if I'd like to retrieve the next root element? If I remember correctly
NestedJ doesn't have a limitation on a number of root elements - there is
no single 0-leveled root node enforced.

Could you check if your logic can work also on 0-leveled nodes and add
tests for it?

Cheers :)
eXsio

śr., 4 wrz 2019, 19:32 użytkownik gregory gincley <notifications@github.com>
napisał:

**Comment by rollenwiese** [comment]
Hi exSio, Thanks I do appreciate this library.

I updated the methods in the NodeRetriever, and created some additional tests for the Root Node scenario. Please let me know what you think.

Updated commit: https://github.com/rollenwiese/nestedj/commit/5a2acd9415e4953c3ab998bc7f60815a38f84564

Thanks,
-Greg

**Comment by eXsio** [comment]
Hello

Looks good, feel free to create PR.

Thanks :)
eXsio

czw., 5 wrz 2019, 19:00 użytkownik gregory gincley <notifications@github.com>
napisał:

**Comment by rollenwiese** [comment]
Will do, and thanks again for creating this library!

**Comment by eXsio** [comment]
PR merged, closing. Thx for the improvement.

**Comment by eXsio** [comment]
Travis Build confirmed stable
