### ISSUE TITLE
Could you provide an example of JpaTreeDiscriminator

### ISSUE THREAD

**Issue by ogarose** [eXsio/nestedj#20]
Hi.

 I can't understand how it is possible to use JpaTreeDiscriminator when the node entity has a field(collumn) with tree_id.
 
 Could you provide an example of how it is possible to implement?
 
 Thanks.

**Comment by eXsio** [comment]
Hello

Please take a look at this topic: https://github.com/eXsio/nestedj/issues/9

JPA version will/should be very similar in its usage of ThreadLocal.

**Comment by ogarose** [comment]
Thanks. It helped me. 

It would be nice to add this example in the README.md
