### ISSUE TITLE
Inserting root level nodes

### ISSUE THREAD

**Issue by Smartel1** [eXsio/nestedj#4]
I can’t find a way to insert node on the top level of hierarchy. It would be great to allow calling insert() method with null parent parameter

**Comment by eXsio** [comment]
If you have an empty tree, you can just persists a node with left 1, right 2, level 0.

If you have at least one root node and you want to create another, use one of those:

> void insertAsNextSiblingOf(N node, N parent);

> void insertAsPrevSiblingOf(N node, N parent);

Depenging whether you want to insert the new root node before or after the existing one. Nested Set is an ordered tree after all :)

**Comment by Smartel1** [comment]
Thx for reply! Your library is great

**Comment by Smartel1** [comment]
Okay, but in this case I need to get existing root node, check whether it exists, and finally call insertAsNextSibling(). I want repository to do this work for me.

It could be easier and faster if it will be a method insertAsLastRootNode() which would  extract max(treeRight) and fill my conflict’s treeLeft = maxTreeRight + 1, treeRight = maxTreeRight + 2.

**Comment by eXsio** [comment]
Done in 4.1.0. New methods are:
- insertAsFirstRoot
- insertAsLastRoot

hope they'll cover your needs :)

**Comment by Smartel1** [comment]
Much appreciated!
