### ISSUE TITLE
can JdbcTreeDiscriminator get Parameters dynamic？

### ISSUE THREAD

**Issue by aeroyu** [eXsio/nestedj#9]
only support const Parameters is not convenience.
my case is table has Polymorphism field，ex container_type and container_id, and the row with  container_type - container_id should be independent tree

**Comment by eXsio** [comment]
I don't understand the example, could you elaborate and supply some code?

What would you like to pass to the discriminator?

**Comment by aeroyu** [comment]
ex
container_type| container_id
User|1
User|2
means very user should have independent tree

**Comment by eXsio** [comment]
We can't pass an instance of NestedNode to the Discriminator, as sometimes we don't have an access to it (ex in rebuilder).

We can however make the discriminator more dynamic:

```java

public class YourJdbcTreeDiscriminator implements JdbcTreeDiscriminator {
    
    private final ThreadLocal<Long> containerId = new ThreadLocal<>();
    
    public void setContainerId(Long containerId) {
        this.containerId.set(containerId);
    }

    @Override
    public String getQueryPart() {
        return "container_id = ?";
    }

    @Override
    public List<Object> getParameters() {
        Long containerId = this.containerId.get();
        Preconditions.checkNotNull(containerId, "ContainerId must be set");
        return Lists.newArrayList(containerId);
    }
}

```

**Comment by aeroyu** [comment]
thx for reply，i try it

**Comment by aeroyu** [comment]
it works ,thx

**Comment by eXsio** [comment]
Np.
